[package]
name = "mowereligible"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
directories = "5.0.1"
rand = "0.8.5"
reqwest = "0.12.7"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }

